### ISSUE TITLE
Question about Raft

### ISSUE THREAD

**Issue by romeolandry** [conduktor/kafka-stack-docker-compose#106]
I don't have an but a question.

I wont to know if you plan  deliver container with Kafka-Raft and a guide to migrate from Zookeeper to Kraft.

Thanks.

**Comment by syntaxbender** [comment]
I know kraft is ready to production since kafka 3.3. I need a full documentation for kafka cluster with kraft. 

"2022/10: KRaft mode declared production-ready in Kafka 3.3"

Can you help? Thanks a lot.

**Comment by AurelieMarcuzzo** [comment]
Hi, as this is not an issue related with Conduktor, I'll close it. Thanks.
