### ISSUE TITLE
Why not using host.docker.internal instead of ${DOCKER_HOST_IP:-127.0.0.1}

### ISSUE THREAD

**Issue by KhASQ** [conduktor/kafka-stack-docker-compose#111]
Hi 

I just wondered why not using host.docker.internal in the YAML files to avoid any need to export the current host IP 

For windows at least 

I ask this question because I did change it in the YAML and everything seems to work fine until now

**Comment by charlescd** [comment]
Can you please provide more infos about your setup?

1. Which OS are you using (Windows as I understand)
2. Which is your version of docker
3. Are you using docker toolbox or docker for Windows?
4. Do you have a small scenario to reproduce? For example, are you trying to connect from the host to kafka? On which IP?
