### ISSUE TITLE
Auto-create Topics as part of docker-compose

### ISSUE THREAD

**Issue by buffaloDeveloper** [conduktor/kafka-stack-docker-compose#116]
Is there a variable that can be set in docker-compose to auto create topics?  I don't see anything in the documentation.

**Comment by OneCricketeer** [comment]
The Confluent images don't support an environment variable for this, only the wurstmeister containers do.

Otherwise, you could use minikube instead, for example, and run Strimzi or Confluent Operator and create topics with kubernetes resource files rather than just variables
