### ISSUE TITLE
Not able to connect from remote computer.

### ISSUE THREAD

**Issue by edgarjoao** [conduktor/kafka-stack-docker-compose#117]
Hi there,
I do have two computer one of them is running docker with [zk-single-kafka-single.yml](https://github.com/conduktor/kafka-stack-docker-compose/blob/master/zk-single-kafka-single.yml) version.

Using https://www.kafkatool.com/ I'm trying to connect from my other computer. 

<img width="812" alt="image" src="https://user-images.githubusercontent.com/2808356/194927463-bcdbe68a-7771-4202-8045-476fa6cb42be.png">

I was able to connect in the computer where docker is running but not the external one.

I was able to ping and telnet to zookeeper port and bootstrap port.

Any suggestion here?

Thanks

**Comment by OneCricketeer** [comment]
Ping and telnet don't accurately test Kafka protocol. It's good the ports are open, but you need to modify the file to use different values, such as your computer's LAN ip - https://www.confluent.io/blog/kafka-listeners-explained/
