### ISSUE TITLE
Conductor credentials don't work for me 

### ISSUE THREAD

**Issue by Anton-Bondar** [conduktor/kafka-stack-docker-compose#119]
Hi ! Up full stack: 
`docker-compose -f full-stack.yml up`

Tried to sign in local conductor with credentials from README:
login: login@admin.io password: admin

But it's not work

![image](https://user-images.githubusercontent.com/8080014/200194958-1928cff2-f183-49a6-ba26-26e295373e88.png)

**Comment by mitchell-h** [comment]
Hi @Anton-Bondar,

The default username for Conduktor-platform when using the full-stack.yml config is Username: admin@admin.io Password:admin .  You can verify the config at https://github.com/conduktor/kafka-stack-docker-compose/blob/master/full-stack.yml#L148
