### ISSUE TITLE
conduktor-platform container sends admin email address to company

### ISSUE THREAD

**Issue by Dirk-Peters-BF** [conduktor/kafka-stack-docker-compose#124]
see title

This and the resulting contact with conduktor employees by email and linkedin is unexpected and does not create trust that other data is safe when the container is part of a production setup.

**Comment by sderosiaux** [comment]
Hi Dirk, your data are clearly safe, please check https://docs.conduktor.io/platform/miscellaneous/data-security for more details. I understand your concerns, but I can assure you we're dealing with data security seriously. We clearly don't want your data flowing to our Cloud systems when you're using our on-premise solution, that would be totally wrong.

**Comment by Dirk-Peters-BF** [comment]
Your data security statement is obviously wrong, because data (my email address) left my local container and has been used by you.

For now, this is one of the reasons, why conduktor has been removed from any potential kafka stack I would setup.

Why is it not possible to switch off sending the admin email address?
