### ISSUE TITLE
wth is this?

### ISSUE THREAD

**Issue by Crownss** [conduktor/kafka-stack-docker-compose#129]
https://res.cloudinary.com/rubbyapi/image/upload/v1678936377/Screenshot_2023-03-16_at_10.07.39_wpiaqy.png

`/var/lib/docker/overlay2/6721998d7c221389aca5750aad126787c1d31f1e6e4f67f41c9e349c5e019ce9/diff/tmp/.V_12186/c3pool/xmrig
/var/lib/docker/overlay2/6721998d7c221389aca5750aad126787c1d31f1e6e4f67f41c9e349c5e019ce9/merged/tmp/.V_12186/c3pool/xmrig`

you guys using docker for mining xmr? and that image are hidden in docker hub
https://hub.docker.com/search?q=confluentinc%2Fcp-zookeeper%3A7.3.2
https://hub.docker.com/search?q=confluentinc%2Fcp-kafka%3A7.3.2

**Comment by OneCricketeer** [comment]
This repo doesn't create/manage Confluent Docker images.

Besides, those images run as `appuser` account, but `kluwy`
