### ISSUE TITLE
Access issue to explore your Kafka data 

### ISSUE THREAD

**Issue by nz185011** [conduktor/kafka-stack-docker-compose#130]
I followed the readme to run the full stack. I log in with admin@admin.io to http://localhost:8080/home/ 
I get the User 'admin@admin.io' does not have 'platform.licenses.read' access to 'platform:/' 
when I go to explore your Kafka data. Does this solution require any license?

**Comment by AurelieMarcuzzo** [comment]
Hi, I think this issue is solved now, feel free to give it a try.
