### ISSUE TITLE
Error configuring rabbitmq-kafka connector

### ISSUE THREAD

**Issue by amsteromer** [conduktor/kafka-stack-docker-compose#135]
Hey, im trying to configure this connector:
```

 {
   "name" : "RabbitMQSourceConnector1",
   "config" : {
     "connector.class" : "io.confluent.connect.rabbitmq.RabbitMQSourceConnector",
     "tasks.max" : "1",
     "rabbitmq.host" : "192.168.1.52",
     "rabbitmq.username" : "guest",
     "rabbitmq.password" : "guest",
     "confluent.topic.bootstrap.servers": "192.168.1.52:9092",
     "kafka.topic" : "TopicName",
     "rabbitmq.queue" : "TopicName"
   }
 }

```

and I'm getting this warning/error on the kafka-connect container:

`[2023-08-30 13:53:47,892] WARN [AdminClient clientId=RabbitMQSourceConnector1-license-manager] Connection to node 1 (/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)`

**Comment by OneCricketeer** [comment]
Hi. Conduktor doesn't package or support this Connector. Please contact Confluent support instead
