### ISSUE TITLE
Support for kafkaiui

### ISSUE THREAD

**Issue by saireddyb** [conduktor/kafka-stack-docker-compose#138]
It will be help full if kafka ui contianer is also added in this docker compose.

**Comment by saireddyb** [comment]
https://github.com/conduktor/kafka-stack-docker-compose/blob/master/zk-single-kafka-single.yml

I was looking for a kafka ui in this docker compse file and I am not able to see conduktor ui also.

**Comment by AurelieMarcuzzo** [comment]
Feel free to get the `postgres` and `conduktor-console` snippets from `conduktor.yml` and put them in your other YAML file.
