### ISSUE TITLE
ubuntu_kafka1_1_fa91fb287f60 exited with code 137

### ISSUE THREAD

**Issue by ricardo-elevenpaths** [conduktor/kafka-stack-docker-compose#39]
Hello,

I'm trying to use it in a NAT network with Vbox, steps:

docker-compose -f zk-single-kafka-single.yml down
export DOCKER_HOST_IP=10.0.2.8
rm -rf zk-single-kafka-single
docker-compose -f zk-single-kafka-single.yml up

...
icaStateMachine)
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:56,658] INFO [PartitionStateMachine controllerId=1] Initializing partition state (kafka.controller.PartitionStateMachine)
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:56,703] INFO [PartitionStateMachine controllerId=1] Triggering online partition state changes (kafka.controller.PartitionStateMachine)
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:56,749] INFO [PartitionStateMachine controllerId=1] Started partition state machine with initial state -> Map() (kafka.controller.PartitionStateMachine)
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:56,756] INFO [Controller id=1] Ready to serve as the new controller with epoch 1 (kafka.controller.KafkaController)
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:56,813] INFO [RequestSendThread controllerId=1] Controller 1 connected to kafka1:19092 (id: 1 rack: null) for sending state change requests (kafka.controller.RequestSendThread)
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:56,835] INFO [Controller id=1] Removing partitions Set() from the list of reassigned partitions in zookeeper (kafka.controller.KafkaController)
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:56,855] INFO [Controller id=1] No more partitions need to be reassigned. Deleting zk path /admin/reassign_partitions (kafka.controller.KafkaController)
zoo1_1_b1281ae2f3c5 | 2018-12-20 11:42:57,099 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@596] - Got user-level KeeperException when processing sessionid:0x167cb6c42c90001 type:multi cxid:0x36 zxid:0x1e txntype:-1 reqpath:n/a aborting remaining multi ops. Error Path:/admin/reassign_partitions Error:KeeperErrorCode = NoNode for /admin/reassign_partitions
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:57,531] INFO [Controller id=1] Partitions undergoing preferred replica election:  (kafka.controller.KafkaController)
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:57,762] INFO [Controller id=1] Partitions that completed preferred replica election:  (kafka.controller.KafkaController)
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:57,764] INFO [Controller id=1] Skipping preferred replica election for partitions due to topic deletion:  (kafka.controller.KafkaController)
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:57,803] INFO [Controller id=1] Resuming preferred replica election for partitions:  (kafka.controller.KafkaController)
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:57,822] INFO [Controller id=1] Starting preferred replica leader election for partitions  (kafka.controller.KafkaController)
zoo1_1_b1281ae2f3c5 | 2018-12-20 11:42:57,956 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@596] - Got user-level KeeperException when processing sessionid:0x167cb6c42c90001 type:multi cxid:0x38 zxid:0x1f txntype:-1 reqpath:n/a aborting remaining multi ops. Error Path:/admin/preferred_replica_election Error:KeeperErrorCode = NoNode for /admin/preferred_replica_election
kafka1_1_fa91fb287f60 | [2018-12-20 11:42:58,213] INFO [Controller id=1] Starting the controller scheduler (kafka.controller.KafkaController)
kafka1_1_fa91fb287f60 | [2018-12-20 11:44:14,887] WARN Client session timed out, have not heard from server in 4631ms for sessionid 0x167cb6c42c90001 (org.apache.zookeeper.ClientCnxn)
kafka1_1_fa91fb287f60 | [2018-12-20 11:45:42,158] INFO Client session timed out, have not heard from server in 4631ms for sessionid 0x167cb6c42c90001, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
zoo1_1_b1281ae2f3c5 | 2018-12-20 11:44:51,281 [myid:] - INFO  [SessionTracker:ZooKeeperServer@358] - Expiring session 0x167cb6c42c90001, timeout of 6000ms exceeded
zoo1_1_b1281ae2f3c5 | 2018-12-20 11:46:44,050 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@487] - Processed session termination for sessionid: 0x167cb6c42c90001
zoo1_1_b1281ae2f3c5 | 2018-12-20 11:46:44,075 [myid:] - INFO  [SyncThread:0:NIOServerCnxn@1008] - Closed socket connection for client /172.20.0.3:48598 which had sessionid 0x167cb6c42c90001
zoo1_1_b1281ae2f3c5 | 2018-12-20 11:46:44,088 [myid:] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@213] - Ignoring unexpected runtime exception
zoo1_1_b1281ae2f3c5 | java.nio.channels.CancelledKeyException
zoo1_1_b1281ae2f3c5 |   at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
zoo1_1_b1281ae2f3c5 |   at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
zoo1_1_b1281ae2f3c5 |   at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:182)
zoo1_1_b1281ae2f3c5 |   at java.lang.Thread.run(Thread.java:745)
ubuntu_kafka1_1_fa91fb287f60 exited with code 137

ifconfig:

br-7904a60fc3b9: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.20.0.1  netmask 255.255.0.0  broadcast 172.20.255.255
        inet6 fe80::42:c6ff:fea5:a632  prefixlen 64  scopeid 0x20<link>
        ether 02:42:c6:a5:a6:32  txqueuelen 0  (Ethernet)
        RX packets 1  bytes 28 (28.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12  bytes 936 (936.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:77:11:f2:5e  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.8  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fe2e:488c  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:2e:48:8c  txqueuelen 1000  (Ethernet)
        RX packets 282686  bytes 388713407 (388.7 MB)
        RX errors 1795  dropped 0  overruns 0  frame 0
        TX packets 32242  bytes 2453771 (2.4 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 9  base 0xd020

Thank you in advance

**Comment by simplesteph** [comment]
I can't reproduce sorry... unsure what's happening? 
Try using a previous tag for example https://github.com/simplesteph/kafka-stack-docker-compose/tree/v5.0.0
