### ISSUE TITLE
How to add other connectors?

### ISSUE THREAD

**Issue by vdj69** [conduktor/kafka-stack-docker-compose#78]
Hi, how to add connectors like Cassandra, MQTT, InfluxDB, and MongoDB. In the list, there are only limited connectors? Also is there any way to secure this page by using username: password?

![image](https://user-images.githubusercontent.com/70035900/106271497-9f57b680-6255-11eb-9264-df57ce867ce5.png)

**Comment by simplesteph** [comment]
**Q: How do I add connectors to kafka connect?**

Create a `connectors` directory and place your connectors there (usually in a subdirectory) `connectors/example/my.jar`

The directory is automatically mounted by the `kafka-connect` Docker container
