### ISSUE TITLE
How can I use this to deploy Kafka with Kubernetes

### ISSUE THREAD

**Issue by Sourabh25** [conduktor/kafka-stack-docker-compose#98]
I am trying to deploy Kafka with same configuration with kubernetes but getting the below error:

 Error while fetching metadata with correlation id 5581 : {toiicName=LEADER_NOT_AVAILABLE} ","traceID":"","spanID":"","trace_id":"","span_id":"","dd.trace_id":"","dd.span_id":"","pid": "org.springframework.kafka.KafkaListenerEndpointContainer#10-0-C-1","logger.thread_name":"[tainer#10-0-C-1]","loggepr.name":"org.apache.kafka.clients.NetworkClient"}

Could you please tell me what I am missing.

Please find below my deployment yaml file

kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-broker0:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_CREATE_TOPICS
              value: "topic:1:1"
---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka
    id: "0"

**Comment by simplesteph** [comment]
This is not for deploying to Kubernetes, this is for local deployment only. We can't help you deploy Kafka to Kubernetes here, sorry..
